#ifndef _CONFIGURATION_H_
#define _CONFIGURATION_H_


#define PIN_LED1 GPIO_PIN_0 
#define PIN_LED2 GPIO_PIN_1
#define PIN_MOTOR_A1 GPIO_PIN_0
#define PIN_MOTOR_A2 GPIO_PIN_8
#define PIN_PART_DET GPIO_PIN_12
#define PIN_OW GPIO_PIN_7
#define PIN_MOTOR_EN GPIO_PIN_6
#define PIN_RPOS GPIO_PIN_3
#define PIN_CPOS GPIO_PIN_4
#define PIN_SW_B GPIO_PIN_1

#endif